#!/usr/bin/env bash

source .env

$PHP_BIN -v
$COMPOSER_BIN -V

cd /api.skroch.de/httpdocs

# $PHP_BIN artisan down --refresh=15 --retry=60

git reset --hard
git clean -d -f
git pull origin master --rebase

$COMPOSER_BIN install --no-dev --no-interaction --prefer-dist --optimize-autoloader

npm ci --audit false
npm run build

# $PHP_BIN artisan storage:link
$PHP_BIN artisan migrate --force
$PHP_BIN artisan optimize:clear
# $PHP_BIN artisan optimize
$PHP_BIN artisan event:cache
$PHP_BIN artisan route:cache
$PHP_BIN artisan view:cache
$PHP_BIN artisan icons:cache

echo "🚀 Application deployed!"
