#!/usr/bin/env bash

if [ ! -f .env ]; then
    echo "The .env file required for deployment does not exist!"
    exit
fi

source .env

if [ "$APP_ENV" == "local" ]; then
    echo "The deployment will only be executed if the value of APP_ENV is not 'local'!"
    exit
fi

# $PHP_BIN artisan down --refresh=15 --retry=60

git reset --hard
git clean -d -f
git pull origin master --rebase

$COMPOSER_BIN install --no-dev --no-interaction --prefer-dist --optimize-autoloader

npm ci --audit false
npm run build

# $PHP_BIN artisan storage:link
$PHP_BIN artisan migrate --force
$PHP_BIN artisan optimize:clear
# $PHP_BIN artisan optimize
$PHP_BIN artisan event:cache
$PHP_BIN artisan route:cache
$PHP_BIN artisan view:cache
# $PHP_BIN artisan icons:cache

echo "🚀 Application deployed!"
